name: Build & test
on:
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nodejs ${{ matrix.note-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm run test
    